### ISSUE TITLE
'function' object has no attribute 'build'

### ISSUE THREAD

**Issue by Ezharjan** [cristal-smac/sumo-experiments#6]
Running your demo code shown in `README` results in error as follows:
```bash
(sumoexp) alex@fst-computer:~/Documents/NewWorks/sumo-experiments$ python demo.py 
Traceback (most recent call last):
  File "/home/alex/Documents/NewWorks/sumo-experiments/demo.py", line 6, in <module>
    exp.run(30, gui=True)
  File "/home/alex/anaconda3/envs/sumoexp/lib/python3.11/site-packages/sumo_experiments/experiment.py", line 58, in run
    self.flows.build(self.files)
    ^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'build'
```

---

 The demo code I run is as follows:
```python
from sumo_experiments import Experiment
from sumo_experiments.preset_networks import OneCrossroadNetwork

network = OneCrossroadNetwork()
exp = Experiment('Test', network.generate_infrastructures, network.generate_flows_all_directions)
exp.run(30, gui=True)
exp.clean_files()
```

**How to fix the problem of `AttributeError: 'function' object has no attribute 'build'`**

**Comment by JulesBompard** [comment]
Hi,
It seems like the demo code has not been actuated after some changes on the library. There might be the same issue with the jupyter tutorial. I'll soon modify it.
Regards.

**Comment by Ezharjan** [comment]
> Hi, It seems like the demo code has not been actuated after some changes on the library. There might be the same issue with the jupyter tutorial. I'll soon modify it. Regards.

Thanks a lot!

**Comment by JulesBompard** [comment]
I updated the documentation (with a bit of delay). You won't have this problem in the future.

**Comment by Ezharjan** [comment]
> I updated the documentation (with a bit of delay). You won't have this problem in the future.

Thanks!!!
